### ISSUE TITLE
Issues for sickrage connecting to website error

### ISSUE THREAD

**Issue by johanndt** [Toilal/stealthbox#20]
Hi,

I've deployed a docker instance (great work btw!), but am having issues with sickrage failing to connect to various torrent search providers such as rarbg or thepiratebay.

For example sickrage will give errors such as

```
2015-04-24 06:58:17 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

I've looked around if it was a sickrage error, but it seems it might be to do with the version of openssl and/or python installed.

See https://github.com/SiCKRAGETV/sickrage-issues/issues/1231

Alternatively, it could just be as simple as `sudo apt-get install ca-certificates` not being installed. BTW, box user can not run sudo - is this intentional?

**Comment by Toilal** [comment]
Hi @johanndt 

box user can not run sudo, and this is intentional. If you need root access, you can use this docker command from your host : `docker exec -it stealthbox bash`.

You can try to fix this issue using root, please report if you find a working solution. From Sickrage issue tracker, it seems upgrading to latest python version works.

There's two option : 
- Change Dockerfile baseimage to `ubuntu:15.04`, which embeds python 2.7.9 as system one.
- Use a compiled and manually installed version of python 2.7.9.

**Comment by Toilal** [comment]
I think next release will fix #18 and this one by upgrading to ubuntu:15.04 (Maybe sunday afternoon)

**Comment by johanndt** [comment]
Hi,

Yeah - I realize about sudo. Also I have been trying to build my own image to fix things. I tried to manually upgrade the python modules for requests, urllib3 and pyopenssl to see if that made any difference. But it didn't.

I might try the 15.04 base image today and see if that makes any difference. I will let you know if I do. I'm just not sure if there would be any "phusion"isms to be aware of when changing the base image. There seems to be some forks of phusion base image to newer versions of Ubuntu which I might give a try too.

Oh, I found another "bug". The `ADD /folder/* /some/folder` type lines doesn't seem to work with my version of docker `Docker version 1.0.1, build 990021a`. This is the default docker version which comes with apt-get in Ubuntu 14.04.2 LTS.  If I take off the `*` or replace it with `.` then it works, eg `ADD /folder/. /some/folder`.

**Comment by Toilal** [comment]
I did not realize before, but you are right : it is harder than it seems to be because of `phusion/baseimage` ... Maybe the second option is more appropriate then (use a custom compiled python version). (`phusion/baseimage` is Ubuntu LTS based, see https://github.com/phusion/baseimage-docker/issues/212)

But please tell me if your are able to run it using 15.04, and if it fixes the problem.

For custom python version, [pyenv](https://github.com/yyuu/pyenv) is a great python environment manager to build any python version we need.

Nowaday, using docker from default LTS package is really deprecated. Use this [PPA](http://www.ubuntuupdates.org/ppa/docker) and install latest package (lxc-docker).

**Comment by johanndt** [comment]
Okay, I tried just ubuntu directly, but as we suspected there were dramas with the init system - I would have to modify your script too much.

So then I tried to make my own version of pushion/baseimage-docker. It was really easy and seemed to work. However I didn't go to 15.04 - I went to 14.10 Utopic, because the deluge ppa don't support the latest version yet - only utopic.

So I built my custom phusion image, and then built stealthbox using that as the base. All went well.

Python is only version 2.7.8, but the SSL connections are now working perfectly in sickrage. Deluge is working too. However I haven't tested anything else yet.

We have a bit of a problem now though - if we go this way, then your docker file depends on a custom base image. Do you want to maintain 2 images? Or possibly, just incorporate the phusion Dockerfile at the beginning of yours - it's very short!

I'll let you decide. :-)

**Comment by Toilal** [comment]
:+1: Thanks very much for reporting this !

I think i'll change the image to use a manual build of python (2.7.9) using pyenv. (while keeping `phusion/baseimage` untouched)

**Comment by johanndt** [comment]
Just another update. I've been running under 14.10 Utopic, and everything works fine except Pydio. It doesn't load at all, so I expect there to be some php5-fpm issues or something. I haven't really dug into it since I don't really use it, but I thought I'd just leave this here as something to be tested when you ever upgrade to a newer ubuntu down the road.
